<a href="https://colab.research.google.com/github/ferdinano/Aprendizaje_automatico_2026/blob/main/Clase2/%20Ejercicios_Clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 2 Ejercicios

Tu tarea es utilizar la librería PANDAS para importar estos datos desde los diferentes formatos (CSV, JSON y Excel), combinarlos en una estructura de datos adecuada y realizar las siguientes acciones:

1. Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.

In [1]:
# Importamos panda
import pandas as pd

In [12]:
datos_csv = pd.read_csv('/content/ventas (1).csv', encoding = "ISO-8859-1")
datos_csv.head()

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.

In [3]:
datos_json = pd.read_json('/content/clientes.json')
datos_json.head()

   id_cliente        nombre             email   telefono
0           1    Juan Pérez    juan@email.com  123456789
1           2   María López   maria@email.com  987654321
2           3  Carlos Gómez  carlos@email.com  456123789

In [4]:
# mostrar cantidad de datos por columnas
datos_json.count()

id_cliente    3
nombre        3
email         3
telefono      3
dtype: int64

In [5]:
# mostrar cantidad solo clientes
datos_json['id_cliente'].count()

np.int64(3)

3. Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos.

In [7]:
# lectura de datos en xlsx
datos_excel = pd.read_excel('/content/inventario.xlsx')
datos_excel.head()

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300

In [8]:
# realizamos el promedio por categorias
datos_excel.groupby('categoria')['stock'].mean()

categoria
Accesorios     40.0
Electrónica    12.5
Name: stock, dtype: float64